import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class Day6Test {

    private Day6 day6;

    @Before
    public void setUp() throws Exception {
        day6 = new Day6();
    }

    @Test
    public void es1Acceptance() {
        String input = "COM)B\n" +
                "B)C\n" +
                "C)D\n" +
                "D)E\n" +
                "E)F\n" +
                "B)G\n" +
                "G)H\n" +
                "D)I\n" +
                "E)J\n" +
                "J)K\n" +
                "K)L";
        Assert.assertEquals(42, day6.evaluateOrbits(input));
    }

    @Test
    public void es2Acceptance() {
        String input = "COM)B\n" +
                "B)C\n" +
                "C)D\n" +
                "D)E\n" +
                "E)F\n" +
                "B)G\n" +
                "G)H\n" +
                "D)I\n" +
                "I)SAN\n" +
                "E)J\n" +
                "J)K\n" +
                "K)YOU\n" +
                "K)L";
        Assert.assertEquals(4, day6.evaluateOrbitsBetweenMeAndSanta(input));
    }

    @Test
    public void es1() {
        String input = "S5F)4L5\n" +
                "7BP)2V1\n" +
                "DHC)KGY\n" +
                "JZG)PN7\n" +
                "RV4)123\n" +
                "2DJ)LPW\n" +
                "19G)31B\n" +
                "H4Z)TC6\n" +
                "3YP)XTQ\n" +
                "H9Q)QXJ\n" +
                "R77)3FM\n" +
                "JD3)GXY\n" +
                "3WS)YHL\n" +
                "X9K)BWP\n" +
                "656)7PW\n" +
                "9S2)LGY\n" +
                "CZB)VXR\n" +
                "1YS)Y5H\n" +
                "1XY)L9Y\n" +
                "NH1)YW5\n" +
                "HVD)2PS\n" +
                "Y1C)4SY\n" +
                "LKH)1PV\n" +
                "7HZ)GZD\n" +
                "TJZ)WV7\n" +
                "V8K)Z28\n" +
                "DB4)S1Q\n" +
                "TRV)4TM\n" +
                "3L3)6YN\n" +
                "LD1)4PR\n" +
                "1XP)3YF\n" +
                "B6Q)QRX\n" +
                "QSL)JV7\n" +
                "MFC)QSJ\n" +
                "TC2)9JZ\n" +
                "PLS)2TK\n" +
                "T6Y)DNB\n" +
                "HDT)BY7\n" +
                "44G)FF3\n" +
                "682)PLS\n" +
                "91Z)DNX\n" +
                "WKK)JWP\n" +
                "FF3)F32\n" +
                "CGL)F92\n" +
                "YCF)8XZ\n" +
                "VKQ)J6C\n" +
                "DP4)6JF\n" +
                "DWB)5RF\n" +
                "5TG)WRP\n" +
                "LWN)N2C\n" +
                "5QB)34Z\n" +
                "LK9)FB9\n" +
                "VK9)WQM\n" +
                "PLR)DP7\n" +
                "BLV)KL4\n" +
                "2XT)R7V\n" +
                "CP3)TJT\n" +
                "7GT)1XP\n" +
                "5J1)Z44\n" +
                "Z8V)MDX\n" +
                "RQK)RVX\n" +
                "K55)PSY\n" +
                "LK4)2CR\n" +
                "3FL)L74\n" +
                "BDW)531\n" +
                "XQZ)GST\n" +
                "5DP)7G2\n" +
                "78T)1VZ\n" +
                "H41)4GK\n" +
                "7PW)B9Q\n" +
                "XSH)GF8\n" +
                "QJ8)YTT\n" +
                "RS9)844\n" +
                "GRL)LD1\n" +
                "K2Z)682\n" +
                "961)25P\n" +
                "FT4)2RJ\n" +
                "SCW)P4C\n" +
                "7QD)L3G\n" +
                "K2T)J8P\n" +
                "948)NFS\n" +
                "FB9)M3G\n" +
                "7J9)JLP\n" +
                "T44)PGK\n" +
                "RFG)BKG\n" +
                "NBJ)DZL\n" +
                "6RR)BLV\n" +
                "MCF)5F9\n" +
                "83D)X5V\n" +
                "X3Z)Q8H\n" +
                "1HP)Y7X\n" +
                "THT)S1K\n" +
                "2DL)Z75\n" +
                "9YN)KD7\n" +
                "SKM)6LN\n" +
                "VRY)3RX\n" +
                "ZCB)66N\n" +
                "T95)THD\n" +
                "SYS)3FL\n" +
                "2TK)H9F\n" +
                "CH7)P49\n" +
                "LYT)XDG\n" +
                "FF3)LTR\n" +
                "92Q)C8J\n" +
                "ZRB)MB8\n" +
                "MLT)GK7\n" +
                "2D1)534\n" +
                "2Q9)1GT\n" +
                "4MP)H4Z\n" +
                "VB9)HJJ\n" +
                "RBR)WFF\n" +
                "Y2N)XZS\n" +
                "D2F)FMW\n" +
                "4R6)PJY\n" +
                "2TK)R7K\n" +
                "F8N)ZJ8\n" +
                "R99)4B6\n" +
                "WDW)ZXK\n" +
                "YJM)LWY\n" +
                "CFR)Y1C\n" +
                "3YF)3L3\n" +
                "MT1)LYT\n" +
                "6GC)ZX4\n" +
                "LJ6)LWN\n" +
                "FH1)PP2\n" +
                "L89)Z9V\n" +
                "3W9)BDW\n" +
                "ZYT)RS5\n" +
                "GK7)DNV\n" +
                "2RJ)THS\n" +
                "KGV)N5R\n" +
                "KF8)P78\n" +
                "DM1)2QX\n" +
                "FDZ)LTT\n" +
                "6BG)LRC\n" +
                "HFL)GXZ\n" +
                "LQY)B5J\n" +
                "YD8)7XZ\n" +
                "6BQ)Y1R\n" +
                "MQ9)46Z\n" +
                "DMQ)BZN\n" +
                "F8L)KGV\n" +
                "CG8)YJM\n" +
                "3Q6)JT6\n" +
                "F1T)SX8\n" +
                "GL3)NWX\n" +
                "PTR)4MP\n" +
                "LWY)S92\n" +
                "CQ5)1XY\n" +
                "TM4)8DK\n" +
                "M7B)D1G\n" +
                "27S)YD8\n" +
                "2MY)5LF\n" +
                "MYK)RBR\n" +
                "9ZB)KZF\n" +
                "4G3)CFR\n" +
                "52N)RS9\n" +
                "9PF)687\n" +
                "CGL)XQZ\n" +
                "JRY)T9W\n" +
                "GYT)MMC\n" +
                "JWP)KZ5\n" +
                "TTD)QBG\n" +
                "5LF)53T\n" +
                "C9C)XBY\n" +
                "1JF)F8N\n" +
                "WQM)QHS\n" +
                "17L)3MX\n" +
                "5BP)7FJ\n" +
                "531)D2D\n" +
                "7X9)YMW\n" +
                "9XQ)B6Q\n" +
                "6QG)RHS\n" +
                "GQF)W6N\n" +
                "R3T)SQ3\n" +
                "PRL)KL3\n" +
                "4XW)N2S\n" +
                "1QH)V5H\n" +
                "MXH)82H\n" +
                "8GN)KJT\n" +
                "Y7D)8VF\n" +
                "H8K)9GG\n" +
                "XFM)6B5\n" +
                "R1C)GYT\n" +
                "QG4)YBY\n" +
                "8CR)CKP\n" +
                "R74)ZNT\n" +
                "H9F)RKT\n" +
                "SJN)7FZ\n" +
                "3VH)RSQ\n" +
                "BWB)SF1\n" +
                "H6V)Y1G\n" +
                "ZVG)HFL\n" +
                "VHL)TG2\n" +
                "KNJ)CHP\n" +
                "COM)YCD\n" +
                "X4G)6BG\n" +
                "T62)XM8\n" +
                "QKZ)YPJ\n" +
                "P1X)5F8\n" +
                "7RX)VXM\n" +
                "V93)9S5\n" +
                "HKY)5ZW\n" +
                "QLR)GZZ\n" +
                "N41)WPZ\n" +
                "D94)J9X\n" +
                "SHQ)STJ\n" +
                "N3P)W37\n" +
                "L9Y)K3X\n" +
                "9T5)HVD\n" +
                "L7M)JYG\n" +
                "FBZ)CBW\n" +
                "L78)N12\n" +
                "R6M)2Q9\n" +
                "YJN)HDT\n" +
                "F92)9DM\n" +
                "WPZ)ZT2\n" +
                "GF3)XDB\n" +
                "PCL)HPZ\n" +
                "3TN)NMH\n" +
                "S5D)JKP\n" +
                "KC2)MGQ\n" +
                "MYN)KJF\n" +
                "BZN)7X8\n" +
                "VQY)WB1\n" +
                "73H)61M\n" +
                "6WW)73B\n" +
                "Y1G)SRS\n" +
                "D4C)ZRB\n" +
                "4JT)LK4\n" +
                "79C)PVF\n" +
                "Z5K)6QG\n" +
                "7RG)QNJ\n" +
                "RLM)D26\n" +
                "1Z9)58H\n" +
                "655)JD3\n" +
                "GFV)S8S\n" +
                "XF3)SZW\n" +
                "X6T)B57\n" +
                "RFG)T6X\n" +
                "TC6)MCF\n" +
                "RYF)7J9\n" +
                "4GK)17L\n" +
                "PW2)441\n" +
                "KGY)S75\n" +
                "YD8)LJ6\n" +
                "W5W)SHQ\n" +
                "BDP)K2T\n" +
                "B9Q)4JT\n" +
                "JYX)ZL9\n" +
                "8HW)BBN\n" +
                "QSJ)MT5\n" +
                "T18)GZC\n" +
                "GZD)T5J\n" +
                "VXM)3WS\n" +
                "PGM)N41\n" +
                "WPB)CSZ\n" +
                "4WW)PMQ\n" +
                "M37)L4B\n" +
                "ST4)1XQ\n" +
                "7T9)9YN\n" +
                "5NW)RLM\n" +
                "17N)R8S\n" +
                "8XZ)7RX\n" +
                "CKD)5VM\n" +
                "CBW)83D\n" +
                "LM1)H6Q\n" +
                "K2Y)656\n" +
                "1VZ)NKV\n" +
                "DT8)PPB\n" +
                "N7M)FT4\n" +
                "P2K)5J1\n" +
                "HGB)FDB\n" +
                "BLF)L89\n" +
                "37S)MYD\n" +
                "FFC)YCF\n" +
                "K4Q)77S\n" +
                "6JF)VVP\n" +
                "KLM)8T1\n" +
                "N7M)5V5\n" +
                "FRW)6BQ\n" +
                "B78)35G\n" +
                "91D)W3W\n" +
                "34Z)Z3J\n" +
                "WB1)DY8\n" +
                "L4B)NBJ\n" +
                "N5R)PY8\n" +
                "SVK)R1C\n" +
                "FX2)QSL\n" +
                "N2S)T62\n" +
                "82H)F6M\n" +
                "7FZ)B64\n" +
                "9JZ)8TM\n" +
                "4TM)Q5T\n" +
                "84W)57M\n" +
                "5CL)355\n" +
                "4W4)KTK\n" +
                "23R)V8K\n" +
                "LTT)CQ5\n" +
                "SZW)3GH\n" +
                "XRM)PTR\n" +
                "BT5)Q5H\n" +
                "QJ1)XF3\n" +
                "V9C)ZYT\n" +
                "Y1G)NYQ\n" +
                "DN6)9GX\n" +
                "5ZW)3VH\n" +
                "7LP)5D4\n" +
                "NWX)6VP\n" +
                "D26)BW5\n" +
                "MT5)MMM\n" +
                "QMY)4LX\n" +
                "73B)CGK\n" +
                "PF5)H9Q\n" +
                "MB7)KB1\n" +
                "WTR)1YS\n" +
                "HPZ)FRW\n" +
                "KWJ)XR4\n" +
                "8RN)9T5\n" +
                "KTK)QLR\n" +
                "TFQ)VQY\n" +
                "Q97)3YP\n" +
                "452)L19\n" +
                "T33)WJ9\n" +
                "QG4)459\n" +
                "6WP)QMY\n" +
                "KD7)G1M\n" +
                "YGC)QF3\n" +
                "67W)DT8\n" +
                "RK8)TBP\n" +
                "JKZ)MQ9\n" +
                "KHP)M4P\n" +
                "3RX)MXL\n" +
                "7XZ)VRY\n" +
                "GZC)T3X\n" +
                "S99)5RY\n" +
                "441)GL3\n" +
                "38N)P2K\n" +
                "37J)Z5K\n" +
                "GTT)5G4\n" +
                "QHT)4GJ\n" +
                "1PV)961\n" +
                "5RN)3JQ\n" +
                "H4P)8CR\n" +
                "SSW)LSP\n" +
                "S58)SAN\n" +
                "YHL)PQL\n" +
                "Q8M)9NV\n" +
                "FKZ)VJR\n" +
                "T8J)3TN\n" +
                "4PC)PCL\n" +
                "RS9)THT\n" +
                "3FM)FFJ\n" +
                "8DK)RYF\n" +
                "XTQ)92W\n" +
                "P78)CFW\n" +
                "BW5)PRL\n" +
                "S75)G2N\n" +
                "JKN)3QG\n" +
                "J7G)MD9\n" +
                "SWJ)52N\n" +
                "S8S)9L3\n" +
                "H8X)K2Y\n" +
                "W1R)9PF\n" +
                "5SX)RK8\n" +
                "1HP)3V4\n" +
                "ZCB)BLF\n" +
                "88M)ZGM\n" +
                "QHS)Z6Z\n" +
                "DNV)H6S\n" +
                "SPZ)R9K\n" +
                "Z7M)JKZ\n" +
                "R7V)TJB\n" +
                "WRF)HFN\n" +
                "5JM)DJH\n" +
                "ZN2)RSH\n" +
                "61M)PGM\n" +
                "CBN)8NX\n" +
                "RRW)3SH\n" +
                "LYM)92Q\n" +
                "RJK)XRM\n" +
                "534)S8T\n" +
                "CP1)KNJ\n" +
                "8XZ)C56\n" +
                "SZW)JHV\n" +
                "H9F)5RN\n" +
                "SX8)1L1\n" +
                "74B)4XW\n" +
                "1GT)WDW\n" +
                "64W)PTS\n" +
                "158)7B1\n" +
                "2S3)VFY\n" +
                "TJT)43T\n" +
                "35G)MXP\n" +
                "YY6)R6M\n" +
                "V53)64C\n" +
                "Y29)8WD\n" +
                "QF3)T44\n" +
                "4GJ)W1R\n" +
                "K4Q)CP1\n" +
                "GR4)Q1P\n" +
                "K6J)HHR\n" +
                "R6H)1S1\n" +
                "XMH)GHQ\n" +
                "BWP)ZJ7\n" +
                "274)HKY\n" +
                "553)LLP\n" +
                "T5J)1KT\n" +
                "Q5H)LYM\n" +
                "HQ1)HXW\n" +
                "1GT)PQZ\n" +
                "PPB)TM4\n" +
                "NWG)VXQ\n" +
                "P23)Y14\n" +
                "2PS)37S\n" +
                "2V1)VGY\n" +
                "MYD)2R4\n" +
                "1L1)D85\n" +
                "XDG)39V\n" +
                "MR1)78T\n" +
                "VFK)HN7\n" +
                "6W5)JHS\n" +
                "F32)698\n" +
                "GRB)33M\n" +
                "GX6)SSL\n" +
                "L71)T18\n" +
                "Y7X)6HM\n" +
                "JKN)7Z9\n" +
                "YBY)17N\n" +
                "V29)DP4\n" +
                "FN3)2DJ\n" +
                "33Y)K55\n" +
                "Y63)N9H\n" +
                "T8W)TFQ\n" +
                "XYN)M6D\n" +
                "KSQ)RV4\n" +
                "66N)3W9\n" +
                "Y1R)79C\n" +
                "TG2)MT1\n" +
                "QVR)5DC\n" +
                "3JJ)QKM\n" +
                "698)RNB\n" +
                "6VP)655\n" +
                "8L8)4G9\n" +
                "RS5)VK9\n" +
                "D85)44G\n" +
                "225)7X9\n" +
                "QPD)VG9\n" +
                "39V)5TV\n" +
                "T7S)K4Q\n" +
                "LV1)21W\n" +
                "8R4)6WW\n" +
                "2PR)JRS\n" +
                "D1G)19G\n" +
                "7G2)K6J\n" +
                "2SY)5CL\n" +
                "QPZ)QHT\n" +
                "3SH)H8K\n" +
                "123)YGC\n" +
                "7B1)1XC\n" +
                "SK7)8GN\n" +
                "RNB)5TG\n" +
                "3JQ)WKF\n" +
                "SF1)KC2\n" +
                "P49)JGH\n" +
                "4HQ)X6T\n" +
                "QH4)32W\n" +
                "Y8B)Q7W\n" +
                "SK4)4XH\n" +
                "WYS)CQ3\n" +
                "33M)FBZ\n" +
                "R56)635\n" +
                "CFW)1DL\n" +
                "4L5)R95\n" +
                "6QH)PFR\n" +
                "7Z9)91Z\n" +
                "RDQ)CKV\n" +
                "PVF)MFC\n" +
                "MMM)73H\n" +
                "BHH)LK9\n" +
                "Q5T)FX2\n" +
                "JHV)6WB\n" +
                "8TM)931\n" +
                "JYG)VRC\n" +
                "DXD)Q91\n" +
                "XQ3)R6H\n" +
                "5RL)CKD\n" +
                "92W)F31\n" +
                "SQ3)JYX\n" +
                "Z6Z)XQ3\n" +
                "5RF)P23\n" +
                "DP7)QVR\n" +
                "HXW)C1F\n" +
                "3SH)FVW\n" +
                "WV7)5NW\n" +
                "PNZ)RM4\n" +
                "C56)TS1\n" +
                "BVV)F97\n" +
                "9S5)H5L\n" +
                "355)9GD\n" +
                "YQC)DWZ\n" +
                "FPW)F9K\n" +
                "459)HQ1\n" +
                "YPJ)F1T\n" +
                "XZS)8RN\n" +
                "5V5)DMQ\n" +
                "9HH)3JJ\n" +
                "GZZ)1J8\n" +
                "C41)DHC\n" +
                "H3D)KSQ\n" +
                "J6C)WQD\n" +
                "WM3)CZB\n" +
                "J9X)7J7\n" +
                "CKV)KHJ\n" +
                "53L)96R\n" +
                "PSR)5BP\n" +
                "7X8)TXF\n" +
                "SCW)XC2\n" +
                "DZL)S58\n" +
                "Z9V)LZF\n" +
                "FD8)X4G\n" +
                "9TD)Y31\n" +
                "M4P)LS4\n" +
                "3GH)QKZ\n" +
                "S58)DXN\n" +
                "258)452\n" +
                "31B)DXD\n" +
                "GL3)2MY\n" +
                "9GG)64M\n" +
                "NYQ)9ZB\n" +
                "RM9)3Q6\n" +
                "1S1)6GC\n" +
                "431)W3V\n" +
                "W3V)CSN\n" +
                "QDH)234\n" +
                "52N)MXH\n" +
                "QNJ)1Z9\n" +
                "WJ9)1JF\n" +
                "6WY)CH7\n" +
                "21W)JJR\n" +
                "Y31)5QB\n" +
                "K4V)QPD\n" +
                "TS1)8VX\n" +
                "GR6)HLJ\n" +
                "1KT)7Y5\n" +
                "PSX)64W\n" +
                "YJN)R99\n" +
                "PTG)CM7\n" +
                "1XC)C32\n" +
                "M1T)G48\n" +
                "7XW)TW6\n" +
                "Q7W)TYV\n" +
                "ZWB)X9K\n" +
                "YGM)2Y3\n" +
                "3GH)C1J\n" +
                "6ZQ)4W4\n" +
                "BY7)WRB\n" +
                "BBN)CX6\n" +
                "1XQ)ZC6\n" +
                "G2N)RRW\n" +
                "DT8)7QT\n" +
                "RSH)P2F\n" +
                "JGH)ZGL\n" +
                "XC2)8HW\n" +
                "MD9)JPQ\n" +
                "S92)DFS\n" +
                "B43)PL5\n" +
                "C1W)MYN\n" +
                "QQP)2SY\n" +
                "SRY)S3L\n" +
                "3QG)XYX\n" +
                "XBY)XYN\n" +
                "LS4)53L\n" +
                "V8K)FH1\n" +
                "LZF)SRV\n" +
                "1DL)HDR\n" +
                "Y5H)RM9\n" +
                "931)R77\n" +
                "LYR)666\n" +
                "DFS)C4D\n" +
                "Z28)Y7D\n" +
                "H6B)M1T\n" +
                "CSN)TBD\n" +
                "VMP)5DP\n" +
                "91D)KHP\n" +
                "PLH)LV1\n" +
                "PGK)DB4\n" +
                "2QX)93G\n" +
                "TJB)Z7M\n" +
                "W9K)L71\n" +
                "C8J)9TD\n" +
                "PN7)8JC\n" +
                "94X)FD8\n" +
                "GWY)258\n" +
                "RM4)L64\n" +
                "WPB)1HP\n" +
                "1J8)H6B\n" +
                "NZ5)YY6\n" +
                "4B6)2PR\n" +
                "9NV)W5W\n" +
                "6LN)SJN\n" +
                "GF8)RDQ\n" +
                "P6S)HJ8\n" +
                "G2N)6WP\n" +
                "F92)BVV\n" +
                "JV7)TQL\n" +
                "Q91)PCG\n" +
                "PFR)KF8\n" +
                "Q1P)7BP\n" +
                "L64)6WY\n" +
                "ZRD)PWW\n" +
                "HFN)88M\n" +
                "MZN)SYS\n" +
                "PQL)Y26\n" +
                "234)225\n" +
                "VVP)37J\n" +
                "PL5)T11\n" +
                "CGK)PTG\n" +
                "LZY)Z8V\n" +
                "N9H)P6S\n" +
                "CZQ)FBR\n" +
                "TBP)MLT\n" +
                "LLP)6S5\n" +
                "YTT)9Q6\n" +
                "H6S)SPZ\n" +
                "R9K)XMH\n" +
                "6PY)PLR\n" +
                "4PC)HBK\n" +
                "WFF)W9K\n" +
                "P2F)FTY\n" +
                "F97)SK7\n" +
                "YCD)M6H\n" +
                "2CR)84W\n" +
                "LSP)GTT\n" +
                "Z3J)QQP\n" +
                "CCF)QJ1\n" +
                "YW5)B68\n" +
                "7FJ)83Q\n" +
                "QKM)GQF\n" +
                "ZJ7)752\n" +
                "Y5H)83G\n" +
                "Y14)V53\n" +
                "5G4)LHR\n" +
                "GZZ)MR1\n" +
                "46Z)4HQ\n" +
                "T6X)FMD\n" +
                "FBR)R74\n" +
                "Q8H)3WR\n" +
                "SVK)FKZ\n" +
                "YXD)H4P\n" +
                "NKV)WM3\n" +
                "RDQ)GF3\n" +
                "L3G)CP3\n" +
                "HN7)VHL\n" +
                "HBK)G8C\n" +
                "WRB)WLY\n" +
                "1V8)M37\n" +
                "KHJ)BHH\n" +
                "GL4)D94\n" +
                "XR4)S5D\n" +
                "XM8)ZWB\n" +
                "5RY)2XT\n" +
                "FCM)5DS\n" +
                "KZ5)XXB\n" +
                "T91)Y8B\n" +
                "KNJ)F8L\n" +
                "D2D)ST4\n" +
                "QQ6)TC2\n" +
                "GF3)RJK\n" +
                "69P)7GT\n" +
                "Y26)TJZ\n" +
                "B5J)8L8\n" +
                "NMH)4YK\n" +
                "SXJ)9S2\n" +
                "752)CBN\n" +
                "ZGM)NZ5\n" +
                "S1K)MZN\n" +
                "MMC)Y29\n" +
                "7QT)LM1\n" +
                "8NX)JZG\n" +
                "R95)GR4\n" +
                "ZXK)QQ6\n" +
                "DNX)158\n" +
                "QRX)GR6\n" +
                "LRC)L7M\n" +
                "X5V)SK4\n" +
                "D4C)Y2N\n" +
                "83Q)134\n" +
                "GST)LQR\n" +
                "R7K)6RR\n" +
                "4G9)M8F\n" +
                "C32)5SX\n" +
                "YMW)RPN\n" +
                "HHR)S99\n" +
                "5D4)C9C\n" +
                "SSL)KWJ\n" +
                "FPW)H6V\n" +
                "JT6)Q8M\n" +
                "53T)QDH\n" +
                "4YK)B42\n" +
                "VFY)KLM\n" +
                "HVD)SCW\n" +
                "88F)V93\n" +
                "6S5)5JM\n" +
                "R8S)YBP\n" +
                "2R4)C8G\n" +
                "8VF)WYS\n" +
                "CSZ)SSW\n" +
                "JRB)WXM\n" +
                "ZT2)7HZ\n" +
                "KJT)9DV\n" +
                "M8F)SKM\n" +
                "N12)SXJ\n" +
                "MD9)6QH\n" +
                "9GD)7T9\n" +
                "ZC6)LQY\n" +
                "H6Q)R56\n" +
                "S8T)27S\n" +
                "B68)VFF\n" +
                "P9B)88F\n" +
                "666)PNZ\n" +
                "MXL)NZY\n" +
                "3MX)2M7\n" +
                "3WR)T8J\n" +
                "DNB)VC7\n" +
                "84R)XNZ\n" +
                "656)K4V\n" +
                "BSK)FLM\n" +
                "MB8)B43\n" +
                "K3X)D2J\n" +
                "7J7)JDF\n" +
                "Z44)JMX\n" +
                "QF3)FCM\n" +
                "5F9)VKQ\n" +
                "GXZ)1SF\n" +
                "4JT)4PC\n" +
                "W3W)R3T\n" +
                "PMQ)69P\n" +
                "3YF)9HH\n" +
                "L74)CGL\n" +
                "8T1)VPX\n" +
                "Y26)9XQ\n" +
                "635)SSP\n" +
                "7BP)PF5\n" +
                "9L3)WPB\n" +
                "JLP)YOU\n" +
                "25P)7RG\n" +
                "4R6)YJN\n" +
                "9GD)PSX\n" +
                "T3X)XFM\n" +
                "8JC)CCF\n" +
                "RPN)6FZ\n" +
                "NZY)67W\n" +
                "NXG)GL4\n" +
                "6YN)6NP\n" +
                "GX6)RQK\n" +
                "G48)5RL\n" +
                "CSZ)GX7\n" +
                "YBP)P1X\n" +
                "KJF)CG8\n" +
                "43T)B78\n" +
                "Y5V)SSH\n" +
                "DJH)2DL\n" +
                "KL3)QN4\n" +
                "5DS)4WW\n" +
                "VG9)84R\n" +
                "B64)8M8\n" +
                "6FZ)94X\n" +
                "ZL9)Y5V\n" +
                "68Y)MYK\n" +
                "M7Y)JRY\n" +
                "QSJ)K2Z\n" +
                "JJR)J7G\n" +
                "MXP)1QH\n" +
                "M6H)WRF\n" +
                "64C)FFC\n" +
                "PJY)HGB\n" +
                "ZGL)LKH\n" +
                "687)PSR\n" +
                "7QD)TTD\n" +
                "FLM)QH4\n" +
                "57M)ZRD\n" +
                "WQD)JRB\n" +
                "STJ)N7M\n" +
                "RHS)2D1\n" +
                "NFS)V9C\n" +
                "P4C)NH1\n" +
                "ZJ8)431\n" +
                "D2J)H8X\n" +
                "JDF)C41\n" +
                "64M)H1Z\n" +
                "JRS)T95\n" +
                "WXM)GRB\n" +
                "MK2)8W1\n" +
                "6NP)D4C\n" +
                "N2C)SWJ\n" +
                "TBD)JKN\n" +
                "PTS)FN3\n" +
                "1SF)VJV\n" +
                "6WB)VB9\n" +
                "F9K)M7B\n" +
                "134)1V8\n" +
                "RSQ)GVK\n" +
                "S3L)V29\n" +
                "4SY)DM1\n" +
                "FCM)4G3\n" +
                "QN4)T33\n" +
                "FDB)WKK\n" +
                "PQZ)LZY\n" +
                "HS9)MB7\n" +
                "CHP)74B\n" +
                "LHR)TRV\n" +
                "7Y5)NXG\n" +
                "QBG)JWB\n" +
                "ZWF)T6Y\n" +
                "WKF)BWB\n" +
                "4XH)4R6\n" +
                "JWB)GRL\n" +
                "DWZ)D2F\n" +
                "THD)4DJ\n" +
                "H1Z)GWS\n" +
                "KZF)CCN\n" +
                "VGY)L78\n" +
                "MDX)RFG\n" +
                "HJ8)38N\n" +
                "L9Y)C1W\n" +
                "C8G)VFK\n" +
                "1KT)PLH\n" +
                "CCN)Q97\n" +
                "8VX)WTR\n" +
                "RVX)H3D\n" +
                "PCG)PDC\n" +
                "58H)7XW\n" +
                "MYK)77T\n" +
                "B42)N3P\n" +
                "CKP)HH3\n" +
                "PY8)HS9\n" +
                "844)T91\n" +
                "GHQ)YQC\n" +
                "C1J)GX6\n" +
                "FMW)Y63\n" +
                "9DM)68Y\n" +
                "FFJ)ZVG\n" +
                "CGK)274\n" +
                "CX6)NWG\n" +
                "JPQ)VMP\n" +
                "H5L)BDP\n" +
                "VRC)MK2\n" +
                "CCX)948\n" +
                "JHS)ZWF\n" +
                "B6Q)6W5\n" +
                "R77)FDZ\n" +
                "VJR)FPW\n" +
                "S1Q)GLD\n" +
                "XDB)P9B\n" +
                "3WR)33Y\n" +
                "DZL)T8W\n" +
                "8M8)LYR\n" +
                "TW6)T7S\n" +
                "4PR)7LP\n" +
                "ZNT)553\n" +
                "5F8)S5F\n" +
                "XNZ)F43\n" +
                "32W)N7K\n" +
                "5TV)PW2\n" +
                "BKG)91D\n" +
                "8W1)SRY\n" +
                "5VM)2S3\n" +
                "M6D)CCX\n" +
                "77S)BSK\n" +
                "G8C)CZQ\n" +
                "DXN)23R\n" +
                "LQR)GWY\n" +
                "SHQ)YGM\n" +
                "9DM)SVK\n" +
                "ZYT)YXD\n" +
                "KL4)QG4\n" +
                "HDR)XSH\n" +
                "77T)DN6\n" +
                "HH3)BT5\n" +
                "SSP)QJ8\n" +
                "5G4)ZN2\n" +
                "6HM)H41\n" +
                "JMX)7QD\n" +
                "B57)DWB\n" +
                "3V4)M7Y\n" +
                "HJJ)6PY\n" +
                "WLY)QPZ\n" +
                "G1M)ZCB\n" +
                "VFF)VGC\n" +
                "VJV)X3Z\n" +
                "W37)GFV\n" +
                "X3Z)HGT\n" +
                "FVW)8R4\n" +
                "XYX)6ZQ";
        Assert.assertEquals(140608, day6.evaluateOrbits(input));
    }

    @Test
    public void es2() {
        String input = "S5F)4L5\n" +
                "7BP)2V1\n" +
                "DHC)KGY\n" +
                "JZG)PN7\n" +
                "RV4)123\n" +
                "2DJ)LPW\n" +
                "19G)31B\n" +
                "H4Z)TC6\n" +
                "3YP)XTQ\n" +
                "H9Q)QXJ\n" +
                "R77)3FM\n" +
                "JD3)GXY\n" +
                "3WS)YHL\n" +
                "X9K)BWP\n" +
                "656)7PW\n" +
                "9S2)LGY\n" +
                "CZB)VXR\n" +
                "1YS)Y5H\n" +
                "1XY)L9Y\n" +
                "NH1)YW5\n" +
                "HVD)2PS\n" +
                "Y1C)4SY\n" +
                "LKH)1PV\n" +
                "7HZ)GZD\n" +
                "TJZ)WV7\n" +
                "V8K)Z28\n" +
                "DB4)S1Q\n" +
                "TRV)4TM\n" +
                "3L3)6YN\n" +
                "LD1)4PR\n" +
                "1XP)3YF\n" +
                "B6Q)QRX\n" +
                "QSL)JV7\n" +
                "MFC)QSJ\n" +
                "TC2)9JZ\n" +
                "PLS)2TK\n" +
                "T6Y)DNB\n" +
                "HDT)BY7\n" +
                "44G)FF3\n" +
                "682)PLS\n" +
                "91Z)DNX\n" +
                "WKK)JWP\n" +
                "FF3)F32\n" +
                "CGL)F92\n" +
                "YCF)8XZ\n" +
                "VKQ)J6C\n" +
                "DP4)6JF\n" +
                "DWB)5RF\n" +
                "5TG)WRP\n" +
                "LWN)N2C\n" +
                "5QB)34Z\n" +
                "LK9)FB9\n" +
                "VK9)WQM\n" +
                "PLR)DP7\n" +
                "BLV)KL4\n" +
                "2XT)R7V\n" +
                "CP3)TJT\n" +
                "7GT)1XP\n" +
                "5J1)Z44\n" +
                "Z8V)MDX\n" +
                "RQK)RVX\n" +
                "K55)PSY\n" +
                "LK4)2CR\n" +
                "3FL)L74\n" +
                "BDW)531\n" +
                "XQZ)GST\n" +
                "5DP)7G2\n" +
                "78T)1VZ\n" +
                "H41)4GK\n" +
                "7PW)B9Q\n" +
                "XSH)GF8\n" +
                "QJ8)YTT\n" +
                "RS9)844\n" +
                "GRL)LD1\n" +
                "K2Z)682\n" +
                "961)25P\n" +
                "FT4)2RJ\n" +
                "SCW)P4C\n" +
                "7QD)L3G\n" +
                "K2T)J8P\n" +
                "948)NFS\n" +
                "FB9)M3G\n" +
                "7J9)JLP\n" +
                "T44)PGK\n" +
                "RFG)BKG\n" +
                "NBJ)DZL\n" +
                "6RR)BLV\n" +
                "MCF)5F9\n" +
                "83D)X5V\n" +
                "X3Z)Q8H\n" +
                "1HP)Y7X\n" +
                "THT)S1K\n" +
                "2DL)Z75\n" +
                "9YN)KD7\n" +
                "SKM)6LN\n" +
                "VRY)3RX\n" +
                "ZCB)66N\n" +
                "T95)THD\n" +
                "SYS)3FL\n" +
                "2TK)H9F\n" +
                "CH7)P49\n" +
                "LYT)XDG\n" +
                "FF3)LTR\n" +
                "92Q)C8J\n" +
                "ZRB)MB8\n" +
                "MLT)GK7\n" +
                "2D1)534\n" +
                "2Q9)1GT\n" +
                "4MP)H4Z\n" +
                "VB9)HJJ\n" +
                "RBR)WFF\n" +
                "Y2N)XZS\n" +
                "D2F)FMW\n" +
                "4R6)PJY\n" +
                "2TK)R7K\n" +
                "F8N)ZJ8\n" +
                "R99)4B6\n" +
                "WDW)ZXK\n" +
                "YJM)LWY\n" +
                "CFR)Y1C\n" +
                "3YF)3L3\n" +
                "MT1)LYT\n" +
                "6GC)ZX4\n" +
                "LJ6)LWN\n" +
                "FH1)PP2\n" +
                "L89)Z9V\n" +
                "3W9)BDW\n" +
                "ZYT)RS5\n" +
                "GK7)DNV\n" +
                "2RJ)THS\n" +
                "KGV)N5R\n" +
                "KF8)P78\n" +
                "DM1)2QX\n" +
                "FDZ)LTT\n" +
                "6BG)LRC\n" +
                "HFL)GXZ\n" +
                "LQY)B5J\n" +
                "YD8)7XZ\n" +
                "6BQ)Y1R\n" +
                "MQ9)46Z\n" +
                "DMQ)BZN\n" +
                "F8L)KGV\n" +
                "CG8)YJM\n" +
                "3Q6)JT6\n" +
                "F1T)SX8\n" +
                "GL3)NWX\n" +
                "PTR)4MP\n" +
                "LWY)S92\n" +
                "CQ5)1XY\n" +
                "TM4)8DK\n" +
                "M7B)D1G\n" +
                "27S)YD8\n" +
                "2MY)5LF\n" +
                "MYK)RBR\n" +
                "9ZB)KZF\n" +
                "4G3)CFR\n" +
                "52N)RS9\n" +
                "9PF)687\n" +
                "CGL)XQZ\n" +
                "JRY)T9W\n" +
                "GYT)MMC\n" +
                "JWP)KZ5\n" +
                "TTD)QBG\n" +
                "5LF)53T\n" +
                "C9C)XBY\n" +
                "1JF)F8N\n" +
                "WQM)QHS\n" +
                "17L)3MX\n" +
                "5BP)7FJ\n" +
                "531)D2D\n" +
                "7X9)YMW\n" +
                "9XQ)B6Q\n" +
                "6QG)RHS\n" +
                "GQF)W6N\n" +
                "R3T)SQ3\n" +
                "PRL)KL3\n" +
                "4XW)N2S\n" +
                "1QH)V5H\n" +
                "MXH)82H\n" +
                "8GN)KJT\n" +
                "Y7D)8VF\n" +
                "H8K)9GG\n" +
                "XFM)6B5\n" +
                "R1C)GYT\n" +
                "QG4)YBY\n" +
                "8CR)CKP\n" +
                "R74)ZNT\n" +
                "H9F)RKT\n" +
                "SJN)7FZ\n" +
                "3VH)RSQ\n" +
                "BWB)SF1\n" +
                "H6V)Y1G\n" +
                "ZVG)HFL\n" +
                "VHL)TG2\n" +
                "KNJ)CHP\n" +
                "COM)YCD\n" +
                "X4G)6BG\n" +
                "T62)XM8\n" +
                "QKZ)YPJ\n" +
                "P1X)5F8\n" +
                "7RX)VXM\n" +
                "V93)9S5\n" +
                "HKY)5ZW\n" +
                "QLR)GZZ\n" +
                "N41)WPZ\n" +
                "D94)J9X\n" +
                "SHQ)STJ\n" +
                "N3P)W37\n" +
                "L9Y)K3X\n" +
                "9T5)HVD\n" +
                "L7M)JYG\n" +
                "FBZ)CBW\n" +
                "L78)N12\n" +
                "R6M)2Q9\n" +
                "YJN)HDT\n" +
                "F92)9DM\n" +
                "WPZ)ZT2\n" +
                "GF3)XDB\n" +
                "PCL)HPZ\n" +
                "3TN)NMH\n" +
                "S5D)JKP\n" +
                "KC2)MGQ\n" +
                "MYN)KJF\n" +
                "BZN)7X8\n" +
                "VQY)WB1\n" +
                "73H)61M\n" +
                "6WW)73B\n" +
                "Y1G)SRS\n" +
                "D4C)ZRB\n" +
                "4JT)LK4\n" +
                "79C)PVF\n" +
                "Z5K)6QG\n" +
                "7RG)QNJ\n" +
                "RLM)D26\n" +
                "1Z9)58H\n" +
                "655)JD3\n" +
                "GFV)S8S\n" +
                "XF3)SZW\n" +
                "X6T)B57\n" +
                "RFG)T6X\n" +
                "TC6)MCF\n" +
                "RYF)7J9\n" +
                "4GK)17L\n" +
                "PW2)441\n" +
                "KGY)S75\n" +
                "YD8)LJ6\n" +
                "W5W)SHQ\n" +
                "BDP)K2T\n" +
                "B9Q)4JT\n" +
                "JYX)ZL9\n" +
                "8HW)BBN\n" +
                "QSJ)MT5\n" +
                "T18)GZC\n" +
                "GZD)T5J\n" +
                "VXM)3WS\n" +
                "PGM)N41\n" +
                "WPB)CSZ\n" +
                "4WW)PMQ\n" +
                "M37)L4B\n" +
                "ST4)1XQ\n" +
                "7T9)9YN\n" +
                "5NW)RLM\n" +
                "17N)R8S\n" +
                "8XZ)7RX\n" +
                "CKD)5VM\n" +
                "CBW)83D\n" +
                "LM1)H6Q\n" +
                "K2Y)656\n" +
                "1VZ)NKV\n" +
                "DT8)PPB\n" +
                "N7M)FT4\n" +
                "P2K)5J1\n" +
                "HGB)FDB\n" +
                "BLF)L89\n" +
                "37S)MYD\n" +
                "FFC)YCF\n" +
                "K4Q)77S\n" +
                "6JF)VVP\n" +
                "KLM)8T1\n" +
                "N7M)5V5\n" +
                "FRW)6BQ\n" +
                "B78)35G\n" +
                "91D)W3W\n" +
                "34Z)Z3J\n" +
                "WB1)DY8\n" +
                "L4B)NBJ\n" +
                "N5R)PY8\n" +
                "SVK)R1C\n" +
                "FX2)QSL\n" +
                "N2S)T62\n" +
                "82H)F6M\n" +
                "7FZ)B64\n" +
                "9JZ)8TM\n" +
                "4TM)Q5T\n" +
                "84W)57M\n" +
                "5CL)355\n" +
                "4W4)KTK\n" +
                "23R)V8K\n" +
                "LTT)CQ5\n" +
                "SZW)3GH\n" +
                "XRM)PTR\n" +
                "BT5)Q5H\n" +
                "QJ1)XF3\n" +
                "V9C)ZYT\n" +
                "Y1G)NYQ\n" +
                "DN6)9GX\n" +
                "5ZW)3VH\n" +
                "7LP)5D4\n" +
                "NWX)6VP\n" +
                "D26)BW5\n" +
                "MT5)MMM\n" +
                "QMY)4LX\n" +
                "73B)CGK\n" +
                "PF5)H9Q\n" +
                "MB7)KB1\n" +
                "WTR)1YS\n" +
                "HPZ)FRW\n" +
                "KWJ)XR4\n" +
                "8RN)9T5\n" +
                "KTK)QLR\n" +
                "TFQ)VQY\n" +
                "Q97)3YP\n" +
                "452)L19\n" +
                "T33)WJ9\n" +
                "QG4)459\n" +
                "6WP)QMY\n" +
                "KD7)G1M\n" +
                "YGC)QF3\n" +
                "67W)DT8\n" +
                "RK8)TBP\n" +
                "JKZ)MQ9\n" +
                "KHP)M4P\n" +
                "3RX)MXL\n" +
                "7XZ)VRY\n" +
                "GZC)T3X\n" +
                "S99)5RY\n" +
                "441)GL3\n" +
                "38N)P2K\n" +
                "37J)Z5K\n" +
                "GTT)5G4\n" +
                "QHT)4GJ\n" +
                "1PV)961\n" +
                "5RN)3JQ\n" +
                "H4P)8CR\n" +
                "SSW)LSP\n" +
                "S58)SAN\n" +
                "YHL)PQL\n" +
                "Q8M)9NV\n" +
                "FKZ)VJR\n" +
                "T8J)3TN\n" +
                "4PC)PCL\n" +
                "RS9)THT\n" +
                "3FM)FFJ\n" +
                "8DK)RYF\n" +
                "XTQ)92W\n" +
                "P78)CFW\n" +
                "BW5)PRL\n" +
                "S75)G2N\n" +
                "JKN)3QG\n" +
                "J7G)MD9\n" +
                "SWJ)52N\n" +
                "S8S)9L3\n" +
                "H8X)K2Y\n" +
                "W1R)9PF\n" +
                "5SX)RK8\n" +
                "1HP)3V4\n" +
                "ZCB)BLF\n" +
                "88M)ZGM\n" +
                "QHS)Z6Z\n" +
                "DNV)H6S\n" +
                "SPZ)R9K\n" +
                "Z7M)JKZ\n" +
                "R7V)TJB\n" +
                "WRF)HFN\n" +
                "5JM)DJH\n" +
                "ZN2)RSH\n" +
                "61M)PGM\n" +
                "CBN)8NX\n" +
                "RRW)3SH\n" +
                "LYM)92Q\n" +
                "RJK)XRM\n" +
                "534)S8T\n" +
                "CP1)KNJ\n" +
                "8XZ)C56\n" +
                "SZW)JHV\n" +
                "H9F)5RN\n" +
                "SX8)1L1\n" +
                "74B)4XW\n" +
                "1GT)WDW\n" +
                "64W)PTS\n" +
                "158)7B1\n" +
                "2S3)VFY\n" +
                "TJT)43T\n" +
                "35G)MXP\n" +
                "YY6)R6M\n" +
                "V53)64C\n" +
                "Y29)8WD\n" +
                "QF3)T44\n" +
                "4GJ)W1R\n" +
                "K4Q)CP1\n" +
                "GR4)Q1P\n" +
                "K6J)HHR\n" +
                "R6H)1S1\n" +
                "XMH)GHQ\n" +
                "BWP)ZJ7\n" +
                "274)HKY\n" +
                "553)LLP\n" +
                "T5J)1KT\n" +
                "Q5H)LYM\n" +
                "HQ1)HXW\n" +
                "1GT)PQZ\n" +
                "PPB)TM4\n" +
                "NWG)VXQ\n" +
                "P23)Y14\n" +
                "2PS)37S\n" +
                "2V1)VGY\n" +
                "MYD)2R4\n" +
                "1L1)D85\n" +
                "XDG)39V\n" +
                "MR1)78T\n" +
                "VFK)HN7\n" +
                "6W5)JHS\n" +
                "F32)698\n" +
                "GRB)33M\n" +
                "GX6)SSL\n" +
                "L71)T18\n" +
                "Y7X)6HM\n" +
                "JKN)7Z9\n" +
                "YBY)17N\n" +
                "V29)DP4\n" +
                "FN3)2DJ\n" +
                "33Y)K55\n" +
                "Y63)N9H\n" +
                "T8W)TFQ\n" +
                "XYN)M6D\n" +
                "KSQ)RV4\n" +
                "66N)3W9\n" +
                "Y1R)79C\n" +
                "TG2)MT1\n" +
                "QVR)5DC\n" +
                "3JJ)QKM\n" +
                "698)RNB\n" +
                "6VP)655\n" +
                "8L8)4G9\n" +
                "RS5)VK9\n" +
                "D85)44G\n" +
                "225)7X9\n" +
                "QPD)VG9\n" +
                "39V)5TV\n" +
                "T7S)K4Q\n" +
                "LV1)21W\n" +
                "8R4)6WW\n" +
                "2PR)JRS\n" +
                "D1G)19G\n" +
                "7G2)K6J\n" +
                "2SY)5CL\n" +
                "QPZ)QHT\n" +
                "3SH)H8K\n" +
                "123)YGC\n" +
                "7B1)1XC\n" +
                "SK7)8GN\n" +
                "RNB)5TG\n" +
                "3JQ)WKF\n" +
                "SF1)KC2\n" +
                "P49)JGH\n" +
                "4HQ)X6T\n" +
                "QH4)32W\n" +
                "Y8B)Q7W\n" +
                "SK4)4XH\n" +
                "WYS)CQ3\n" +
                "33M)FBZ\n" +
                "R56)635\n" +
                "CFW)1DL\n" +
                "4L5)R95\n" +
                "6QH)PFR\n" +
                "7Z9)91Z\n" +
                "RDQ)CKV\n" +
                "PVF)MFC\n" +
                "MMM)73H\n" +
                "BHH)LK9\n" +
                "Q5T)FX2\n" +
                "JHV)6WB\n" +
                "8TM)931\n" +
                "JYG)VRC\n" +
                "DXD)Q91\n" +
                "XQ3)R6H\n" +
                "5RL)CKD\n" +
                "92W)F31\n" +
                "SQ3)JYX\n" +
                "Z6Z)XQ3\n" +
                "5RF)P23\n" +
                "DP7)QVR\n" +
                "HXW)C1F\n" +
                "3SH)FVW\n" +
                "WV7)5NW\n" +
                "PNZ)RM4\n" +
                "C56)TS1\n" +
                "BVV)F97\n" +
                "9S5)H5L\n" +
                "355)9GD\n" +
                "YQC)DWZ\n" +
                "FPW)F9K\n" +
                "459)HQ1\n" +
                "YPJ)F1T\n" +
                "XZS)8RN\n" +
                "5V5)DMQ\n" +
                "9HH)3JJ\n" +
                "GZZ)1J8\n" +
                "C41)DHC\n" +
                "H3D)KSQ\n" +
                "J6C)WQD\n" +
                "WM3)CZB\n" +
                "J9X)7J7\n" +
                "CKV)KHJ\n" +
                "53L)96R\n" +
                "PSR)5BP\n" +
                "7X8)TXF\n" +
                "SCW)XC2\n" +
                "DZL)S58\n" +
                "Z9V)LZF\n" +
                "FD8)X4G\n" +
                "9TD)Y31\n" +
                "M4P)LS4\n" +
                "3GH)QKZ\n" +
                "S58)DXN\n" +
                "258)452\n" +
                "31B)DXD\n" +
                "GL3)2MY\n" +
                "9GG)64M\n" +
                "NYQ)9ZB\n" +
                "RM9)3Q6\n" +
                "1S1)6GC\n" +
                "431)W3V\n" +
                "W3V)CSN\n" +
                "QDH)234\n" +
                "52N)MXH\n" +
                "QNJ)1Z9\n" +
                "WJ9)1JF\n" +
                "6WY)CH7\n" +
                "21W)JJR\n" +
                "Y31)5QB\n" +
                "K4V)QPD\n" +
                "TS1)8VX\n" +
                "GR6)HLJ\n" +
                "1KT)7Y5\n" +
                "PSX)64W\n" +
                "YJN)R99\n" +
                "PTG)CM7\n" +
                "1XC)C32\n" +
                "M1T)G48\n" +
                "7XW)TW6\n" +
                "Q7W)TYV\n" +
                "ZWB)X9K\n" +
                "YGM)2Y3\n" +
                "3GH)C1J\n" +
                "6ZQ)4W4\n" +
                "BY7)WRB\n" +
                "BBN)CX6\n" +
                "1XQ)ZC6\n" +
                "G2N)RRW\n" +
                "DT8)7QT\n" +
                "RSH)P2F\n" +
                "JGH)ZGL\n" +
                "XC2)8HW\n" +
                "MD9)JPQ\n" +
                "S92)DFS\n" +
                "B43)PL5\n" +
                "C1W)MYN\n" +
                "QQP)2SY\n" +
                "SRY)S3L\n" +
                "3QG)XYX\n" +
                "XBY)XYN\n" +
                "LS4)53L\n" +
                "V8K)FH1\n" +
                "LZF)SRV\n" +
                "1DL)HDR\n" +
                "Y5H)RM9\n" +
                "931)R77\n" +
                "LYR)666\n" +
                "DFS)C4D\n" +
                "Z28)Y7D\n" +
                "H6B)M1T\n" +
                "CSN)TBD\n" +
                "VMP)5DP\n" +
                "91D)KHP\n" +
                "PLH)LV1\n" +
                "PGK)DB4\n" +
                "2QX)93G\n" +
                "TJB)Z7M\n" +
                "W9K)L71\n" +
                "C8J)9TD\n" +
                "PN7)8JC\n" +
                "94X)FD8\n" +
                "GWY)258\n" +
                "RM4)L64\n" +
                "WPB)1HP\n" +
                "1J8)H6B\n" +
                "NZ5)YY6\n" +
                "4B6)2PR\n" +
                "9NV)W5W\n" +
                "6LN)SJN\n" +
                "GF8)RDQ\n" +
                "P6S)HJ8\n" +
                "G2N)6WP\n" +
                "F92)BVV\n" +
                "JV7)TQL\n" +
                "Q91)PCG\n" +
                "PFR)KF8\n" +
                "Q1P)7BP\n" +
                "L64)6WY\n" +
                "ZRD)PWW\n" +
                "HFN)88M\n" +
                "MZN)SYS\n" +
                "PQL)Y26\n" +
                "234)225\n" +
                "VVP)37J\n" +
                "PL5)T11\n" +
                "CGK)PTG\n" +
                "LZY)Z8V\n" +
                "N9H)P6S\n" +
                "CZQ)FBR\n" +
                "TBP)MLT\n" +
                "LLP)6S5\n" +
                "YTT)9Q6\n" +
                "H6S)SPZ\n" +
                "R9K)XMH\n" +
                "6PY)PLR\n" +
                "4PC)HBK\n" +
                "WFF)W9K\n" +
                "P2F)FTY\n" +
                "F97)SK7\n" +
                "YCD)M6H\n" +
                "2CR)84W\n" +
                "LSP)GTT\n" +
                "Z3J)QQP\n" +
                "CCF)QJ1\n" +
                "YW5)B68\n" +
                "7FJ)83Q\n" +
                "QKM)GQF\n" +
                "ZJ7)752\n" +
                "Y5H)83G\n" +
                "Y14)V53\n" +
                "5G4)LHR\n" +
                "GZZ)MR1\n" +
                "46Z)4HQ\n" +
                "T6X)FMD\n" +
                "FBR)R74\n" +
                "Q8H)3WR\n" +
                "SVK)FKZ\n" +
                "YXD)H4P\n" +
                "NKV)WM3\n" +
                "RDQ)GF3\n" +
                "L3G)CP3\n" +
                "HN7)VHL\n" +
                "HBK)G8C\n" +
                "WRB)WLY\n" +
                "1V8)M37\n" +
                "KHJ)BHH\n" +
                "GL4)D94\n" +
                "XR4)S5D\n" +
                "XM8)ZWB\n" +
                "5RY)2XT\n" +
                "FCM)5DS\n" +
                "KZ5)XXB\n" +
                "T91)Y8B\n" +
                "KNJ)F8L\n" +
                "D2D)ST4\n" +
                "QQ6)TC2\n" +
                "GF3)RJK\n" +
                "69P)7GT\n" +
                "Y26)TJZ\n" +
                "B5J)8L8\n" +
                "NMH)4YK\n" +
                "SXJ)9S2\n" +
                "752)CBN\n" +
                "ZGM)NZ5\n" +
                "S1K)MZN\n" +
                "MMC)Y29\n" +
                "7QT)LM1\n" +
                "8NX)JZG\n" +
                "R95)GR4\n" +
                "ZXK)QQ6\n" +
                "DNX)158\n" +
                "QRX)GR6\n" +
                "LRC)L7M\n" +
                "X5V)SK4\n" +
                "D4C)Y2N\n" +
                "83Q)134\n" +
                "GST)LQR\n" +
                "R7K)6RR\n" +
                "4G9)M8F\n" +
                "C32)5SX\n" +
                "YMW)RPN\n" +
                "HHR)S99\n" +
                "5D4)C9C\n" +
                "SSL)KWJ\n" +
                "FPW)H6V\n" +
                "JT6)Q8M\n" +
                "53T)QDH\n" +
                "4YK)B42\n" +
                "VFY)KLM\n" +
                "HVD)SCW\n" +
                "88F)V93\n" +
                "6S5)5JM\n" +
                "R8S)YBP\n" +
                "2R4)C8G\n" +
                "8VF)WYS\n" +
                "CSZ)SSW\n" +
                "JRB)WXM\n" +
                "ZT2)7HZ\n" +
                "KJT)9DV\n" +
                "M8F)SKM\n" +
                "N12)SXJ\n" +
                "MD9)6QH\n" +
                "9GD)7T9\n" +
                "ZC6)LQY\n" +
                "H6Q)R56\n" +
                "S8T)27S\n" +
                "B68)VFF\n" +
                "P9B)88F\n" +
                "666)PNZ\n" +
                "MXL)NZY\n" +
                "3MX)2M7\n" +
                "3WR)T8J\n" +
                "DNB)VC7\n" +
                "84R)XNZ\n" +
                "656)K4V\n" +
                "BSK)FLM\n" +
                "MB8)B43\n" +
                "K3X)D2J\n" +
                "7J7)JDF\n" +
                "Z44)JMX\n" +
                "QF3)FCM\n" +
                "5F9)VKQ\n" +
                "GXZ)1SF\n" +
                "4JT)4PC\n" +
                "W3W)R3T\n" +
                "PMQ)69P\n" +
                "3YF)9HH\n" +
                "L74)CGL\n" +
                "8T1)VPX\n" +
                "Y26)9XQ\n" +
                "635)SSP\n" +
                "7BP)PF5\n" +
                "9L3)WPB\n" +
                "JLP)YOU\n" +
                "25P)7RG\n" +
                "4R6)YJN\n" +
                "9GD)PSX\n" +
                "T3X)XFM\n" +
                "8JC)CCF\n" +
                "RPN)6FZ\n" +
                "NZY)67W\n" +
                "NXG)GL4\n" +
                "6YN)6NP\n" +
                "GX6)RQK\n" +
                "G48)5RL\n" +
                "CSZ)GX7\n" +
                "YBP)P1X\n" +
                "KJF)CG8\n" +
                "43T)B78\n" +
                "Y5V)SSH\n" +
                "DJH)2DL\n" +
                "KL3)QN4\n" +
                "5DS)4WW\n" +
                "VG9)84R\n" +
                "B64)8M8\n" +
                "6FZ)94X\n" +
                "ZL9)Y5V\n" +
                "68Y)MYK\n" +
                "M7Y)JRY\n" +
                "QSJ)K2Z\n" +
                "JJR)J7G\n" +
                "MXP)1QH\n" +
                "M6H)WRF\n" +
                "64C)FFC\n" +
                "PJY)HGB\n" +
                "ZGL)LKH\n" +
                "687)PSR\n" +
                "7QD)TTD\n" +
                "FLM)QH4\n" +
                "57M)ZRD\n" +
                "WQD)JRB\n" +
                "STJ)N7M\n" +
                "RHS)2D1\n" +
                "NFS)V9C\n" +
                "P4C)NH1\n" +
                "ZJ8)431\n" +
                "D2J)H8X\n" +
                "JDF)C41\n" +
                "64M)H1Z\n" +
                "JRS)T95\n" +
                "WXM)GRB\n" +
                "MK2)8W1\n" +
                "6NP)D4C\n" +
                "N2C)SWJ\n" +
                "TBD)JKN\n" +
                "PTS)FN3\n" +
                "1SF)VJV\n" +
                "6WB)VB9\n" +
                "F9K)M7B\n" +
                "134)1V8\n" +
                "RSQ)GVK\n" +
                "S3L)V29\n" +
                "4SY)DM1\n" +
                "FCM)4G3\n" +
                "QN4)T33\n" +
                "FDB)WKK\n" +
                "PQZ)LZY\n" +
                "HS9)MB7\n" +
                "CHP)74B\n" +
                "LHR)TRV\n" +
                "7Y5)NXG\n" +
                "QBG)JWB\n" +
                "ZWF)T6Y\n" +
                "WKF)BWB\n" +
                "4XH)4R6\n" +
                "JWB)GRL\n" +
                "DWZ)D2F\n" +
                "THD)4DJ\n" +
                "H1Z)GWS\n" +
                "KZF)CCN\n" +
                "VGY)L78\n" +
                "MDX)RFG\n" +
                "HJ8)38N\n" +
                "L9Y)C1W\n" +
                "C8G)VFK\n" +
                "1KT)PLH\n" +
                "CCN)Q97\n" +
                "8VX)WTR\n" +
                "RVX)H3D\n" +
                "PCG)PDC\n" +
                "58H)7XW\n" +
                "MYK)77T\n" +
                "B42)N3P\n" +
                "CKP)HH3\n" +
                "PY8)HS9\n" +
                "844)T91\n" +
                "GHQ)YQC\n" +
                "C1J)GX6\n" +
                "FMW)Y63\n" +
                "9DM)68Y\n" +
                "FFJ)ZVG\n" +
                "CGK)274\n" +
                "CX6)NWG\n" +
                "JPQ)VMP\n" +
                "H5L)BDP\n" +
                "VRC)MK2\n" +
                "CCX)948\n" +
                "JHS)ZWF\n" +
                "B6Q)6W5\n" +
                "R77)FDZ\n" +
                "VJR)FPW\n" +
                "S1Q)GLD\n" +
                "XDB)P9B\n" +
                "3WR)33Y\n" +
                "DZL)T8W\n" +
                "8M8)LYR\n" +
                "TW6)T7S\n" +
                "4PR)7LP\n" +
                "ZNT)553\n" +
                "5F8)S5F\n" +
                "XNZ)F43\n" +
                "32W)N7K\n" +
                "5TV)PW2\n" +
                "BKG)91D\n" +
                "8W1)SRY\n" +
                "5VM)2S3\n" +
                "M6D)CCX\n" +
                "77S)BSK\n" +
                "G8C)CZQ\n" +
                "DXN)23R\n" +
                "LQR)GWY\n" +
                "SHQ)YGM\n" +
                "9DM)SVK\n" +
                "ZYT)YXD\n" +
                "KL4)QG4\n" +
                "HDR)XSH\n" +
                "77T)DN6\n" +
                "HH3)BT5\n" +
                "SSP)QJ8\n" +
                "5G4)ZN2\n" +
                "6HM)H41\n" +
                "JMX)7QD\n" +
                "B57)DWB\n" +
                "3V4)M7Y\n" +
                "HJJ)6PY\n" +
                "WLY)QPZ\n" +
                "G1M)ZCB\n" +
                "VFF)VGC\n" +
                "VJV)X3Z\n" +
                "W37)GFV\n" +
                "X3Z)HGT\n" +
                "FVW)8R4\n" +
                "XYX)6ZQ";
        Assert.assertEquals(337, day6.evaluateOrbitsBetweenMeAndSanta(input));
    }
}